version: '3.8'

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    network_mode: host
    restart: always
    volumes:
      - /mnt/data/openwebui/data:/app/backend/data
    environment:
      # https://docs.openwebui.com/getting-started/advanced-topics/env-configuration/#security-variables
      - ENABLE_SIGNUP=false
      - CORS_ALLOW_ORIGIN=*
      - WEBUI_AUTH=false
      - ENABLE_COMMUNITY_SHARING=false
      - ENABLE_EVALUATION_ARENA_MODELS=false
      - ENABLE_CHANNELS=false
      - ENABLE_MESSAGE_RATING=false
      - OLLAMA_BASE_URL=http://10.0.1.38:11434
      - ENABLE_OPENAI_API=false
      - DEFAULT_LOCALE=fr
      #- WEBUI_URL=10.0.1.38:8080
      - PORT=3000
      # RAG searxng
      - ENABLE_RAG_WEB_SEARCH=True
      - RAG_WEB_SEARCH_ENGINE=searxng
      - RAG_WEB_SEARCH_RESULT_COUNT=3
      - RAG_WEB_SEARCH_CONCURRENT_REQUESTS=10
      - SEARXNG_QUERY_URL=http://10.0.1.38:8080/search?q=<query>
      # ComfyUI
      - COMFYUI_BASE_URL=http://10.0.1.38:8188
      - ENABLE_IMAGE_GENERATION=true
      - IMAGE_GENERATION_ENGINE=comfyui
      - IMAGE_GENERATION_MODEL=cyberrealistic_v41BackToBasics.safetensors
      - IMAGE_SIZE=512x288
      - IMAGE_STEPS=45
networks:
  host:
    external: true
