# docker-compose.yaml
# antoine@ginies.org
# Prepare for AMDGPU!
#version: '3.8'

services:
  api:
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
    image: comfyui
    container_name: comfyui
    network_mode: host
    environment:
      # false, true, debug
      - BUILD=debug
      - PROFILE=gpu
      # adjust to you AMD GPU or Nvidia
      # https://rocm.docs.amd.com/projects/install-on-linux/en/latest/reference/system-requirements.html
      - GPU_TARGETS=gfx1100
      - HSA_OVERRIDE_GFX_VERSION=11.0.0
      - OPTIONS=--listen
    ports:
      - "8188:8188"
    devices:
      - /dev/dri
      - /dev/kfd
    volumes:
      - /mnt/data/models:/ComfyUI/models:/models
      - /home/aginies/Pictures/comfyui:/ComfyUI/output
#      - /home/aginies/LocalAI/images:/stable-diffusion-webui/outputs/txt2img-images
