# docker-compose.yaml
#version: "3.9"

services:
  api:
    image: localai/localai:latest-aio-gpu-hipblas
    privileged: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8080/readyz"]
      interval: 1m
      timeout: 20m
      retries: 5
    ports:
      - 8080:8080
    network_mode: host
    command:
      - --cors
    environment:
      - DEBUG=true
      - REBUILD=false
      - PROFILE=gpu
      - THREADS=12
      - BUILD_PARALLELISM=12
      - BUILD_TYPE=hipblas
      - GPU_TARGETS=gfx1100
      - HSA_OVERRIDE_GFX_VERSION=11.0.0
      - LOCALAI_CORS_ALLOW_ORIGINS=*
    devices:
      # AMD GPU only require the following devices be passed through to the container for offloading to occur.
      - /dev/dri
      - /dev/kfd
    volumes:
      - ./models:/build/models:cached
      - ./images:/tmp/generated/images
